# Generated by Django 2.1.1 on 2018-09-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0005_auto_20180909_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
