# Generated by Django 2.1.1 on 2018-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0007_camera_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='alias',
            field=models.CharField(blank=True, default='My Camera', max_length=100, null=True),
        ),
    ]
