# Generated by Django 2.1.1 on 2018-09-15 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0011_remove_userprofile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
