# Generated by Django 2.1.1 on 2018-09-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0013_auto_20180915_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
